package bench.app.service.userpermission;

public enum UserPermissionQueryType {
    SELECT_MAX_ID,
    CREATE,
    SELECT_MAX_RENTAL_METHOD_ID,
    CREATE_RENTAL_METHOD,
    SELECT_MAX_BOOKSHOP_ID,
    SELECT_MAX_OPENING_HOURS_ID,
    SELECT_ANY_EMPLOYEE_ID,
    CREATE_BOOKSHOP,
    CREATE_BOOKSHOP_OPENING_HOURS,
    UPDATE_BOOKSHOP_OPENING_HOURS_ID,
    SELECT_MAX_BOOKSHOP_USER_ID,
    CREATE_BOOKSHOP_USER,
    SELECT_MAX_USER_CARD_ID,
    CREATE_USER_CARD,
    SELECT_MAX_USER_ACCOUNT_ID,
    CREATE_USER_ACCOUNT,
    SELECT_ANY_ACTIVATION_STATUS_ID,
    SELECT_ANY_PERMISSION_ID,
    // CREATE 5 - Dodanie książek do oferty sklepu
    SELECT_MAX_BOOK_ID,
    CREATE_BOOK,
    SELECT_MAX_BOOKSHOP_OFFERING_ID,
    CREATE_BOOKSHOP_OFFERING,
    SELECT_ANY_BOOK_ID,
    SELECT_ANY_BOOKSHOP_ID,
    // CREATE 6 - Dodanie rezerwacji książki
    SELECT_MAX_BOOK_RESERVATION_ID,
    CREATE_BOOK_RESERVATION,
    SELECT_ANY_BOOKSHOP_USER_ID,
    // CREATE 7 - Utworzenie wypożyczenia z pełnym kontekstem
    SELECT_MAX_RENTAL_ID,
    CREATE_RENTAL_FULL,
    SELECT_ANY_RENTAL_METHOD_ID,
    // CREATE 8 - Warunkowe utworzenie wypożyczenia
    SELECT_ACTIVE_USER_WITH_BOOK_IN_SHOP,
    CREATE_RENTAL_CONDITIONAL,
    // CREATE 9 - Batch dostawy do sklepu
    CREATE_BATCH_SUPPLY,
    READ,
    UPDATE,
    DELETE
}
