services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: unless-stopped
    container_name: mssql
    environment:
      ACCEPT_EULA: "y"
      MSSQL_PID: "EnterpriseDeveloper"
      
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PWD:?}"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -C -U sa -P ${MSSQL_SA_PWD} -Q 'SELECT 1' || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 20s
      start_interval: 10s
    networks:
      - mssql

  mssql-init:
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: no
    container_name: mssql-init
    command: >
      /opt/mssql-tools18/bin/sqlcmd -S mssql -C -U sa -P ${MSSQL_SA_PWD} -Q 'CREATE DATABASE bench' && \
      /opt/mssql-tools18/bin/sqlcmd -S mssql -d bench -C -U sa -P ${MSSQL_SA_PWD} -i /schema/create_schema.sql && \
      /opt/mssql-tools18/bin/sqlcmd -S mssql -d bench -C -U sa -P ${MSSQL_SA_PWD} -i /schema/create_schema_structure.sql
    environment:
      ACCEPT_EULA: "y"
      MSSQL_PID: "EnterpriseDeveloper"

      MSSQL_SA_PASSWORD: "notimportant"
    volumes:
      - "./schema/sql:/schema:ro"
    networks:
      - mssql
    depends_on:
      mssql:
        condition: service_healthy

  postgres:
    image: postgres:18.3
    restart: unless-stopped
    container_name: "postgres"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:?}"
      POSTGRES_PASSWORD: "${POSTGRES_PWD:?}"
      POSTGRES_DB: "${POSTGRES_DB:?}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 20s
      start_interval: 10s
    networks:
      - postgres

  cassandra:
    image: cassandra:5.0.6
    restart: unless-stopped
    container_name: "cassandra"
    environment:
      CASSANDRA_USER: "${CASSANDRA_USER:?}"
      CASSANDRA_PASSWORD: "${CASSANDRA_PWD:?}"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -u ${CASSANDRA_USER} -p ${CASSANDRA_PWD}"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 60s
      start_interval: 60s
    networks:
      - cassandra

  # cassandra doesnt have entrypoint scripts by default
  cassandra-init:
    image: cassandra:5.0.6
    restart: no
    container_name: "cassandra-init"
    command: cqlsh cassandra -f /schema/create_schema.cql
    environment:
      CASSANDRA_USER: "notimportant"
      CASSANDRA_PASSWORD: "notimportant"
    volumes:
      - "./schema/widecolumn:/schema:ro"
    networks:
      - cassandra
    depends_on:
      cassandra:
        condition: service_healthy

  scylla:
    image: scylladb/scylla:2026.1
    restart: unless-stopped
    container_name: "scylla"
    command: "--smp 1 --memory 1G"
    environment:
      CASSANDRA_USER: "${CASSANDRA_USER:?}"
      CASSANDRA_PASSWORD: "${CASSANDRA_PWD:?}"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -u ${CASSANDRA_USER} -p ${CASSANDRA_PWD}"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 60s
      start_interval: 60s
    networks:
      - scylla

  scylla-init:
    image: scylladb/scylla:2026.1
    restart: no
    container_name: "scylla-init"
    entrypoint: "cqlsh scylla -f /schema/create_schema.cql"
    environment:
      CASSANDRA_USER: "notimportant"
      CASSANDRA_PASSWORD: "notimportant"
    volumes:
      - "./schema/widecolumn:/schema:ro"
    networks:
      - scylla
    depends_on:
      scylla:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: "bench.Dockerfile"
      target: runner
    container_name: "backend"
    ports:
      - "8080:8080"
    networks:
      - mssql
      - postgres
      - cassandra
      - scylla
      - external
    depends_on:
      mssql-init:
        condition: service_completed_successfully
#      mssql:
#        condition: service_healthy
      postgres:
        condition: service_healthy
      cassandra-init:
        condition: service_completed_successfully
      scylla-init:
        condition: service_completed_successfully

networks:
  mssql:
    name: mssql
    internal: true
  postgres:
    name: postgres
    internal: true
  cassandra:
    name: cassandra
    internal: true
  scylla:
    name: scylla
    internal: true
  external:
    name: external
