spring:
  application:
    name: bench
  datasource:
    url: jdbc:postgresql://postgres:5432/bench?currentSchema=bench
    username: postgres
    password: "@testtest123A"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: bench
    hibernate:
      ddl-auto: update #validate
    show-sql: false

  cassandra:
    contact-points: cassandra:9042
    keyspace-name: "bench"
    local-datacenter: "datacenter1"
    schema-action: none

app:
  datasource:
    mssql:
      url: jdbc:sqlserver://mssql:1433;databaseName=bench;encrypt=false
      username: sa
      password: "@testtest123A"
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    scylla:
      contact-points: scylla:9042
      keyspace-name: "bench"
      local-datacenter: "datacenter1"
      schema-action: none