spring:
  application:
    name: bench
  datasource:
    url: jdbc:postgresql://postgres:5432/bench
    username: postgres
    password: "@testtest123A"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #validate
    show-sql: false

  cassandra:
    contact-points: cassandra:9042
    keyspace-name: "bench"
    local-datacenter: "datacenter1"
    schema-action: none